FROM mcr.microsoft.com/dotnet/aspnet:7.0 as base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app
COPY ["FarmBank.Api/FarmBank.Api.csproj", "FarmBank.Api/"]
COPY ["FarmBank.Application/FarmBank.Application.csproj", "FarmBank.Application/"]
COPY ["FarmBank.Integration/FarmBank.Integration.csproj", "FarmBank.Integration/"]
COPY *.sln . 
RUN dotnet restore FarmBank.Api/FarmBank.Api.csproj
WORKDIR /app/FarmBank.Api
COPY . .
RUN dotnet build backend.sln -c release -o /app/build 

FROM build As publish
RUN dotnet publish backend.sln -c release -o /app/publish --no-restore

FROM base As final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT [ "dotnet", "FarmBank.Api.dll" ]